name: Deploy Android App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decode Base64 Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > androidApp/release.keystore

      - name: Set up Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Run Fastlane Android Deployment
        env:
          KEYSTORE_FILE: ../androidApp/release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GCP_PLAY_CONSOLE_JSON }}
        run: bundle exec fastlane android deploy_playstore
